FROM node:12.14.0
# FROM node:12.14.0-alpine

# set working directory
WORKDIR /srv/app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /srv/app/node_modules/.bin:$PATH

# install and cache app dependencies
# COPY ./app/package.json /srv/app/package.json
# RUN yarn install --silent

# start app
# CMD ["npm", "start"]
